name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps & build
        run: |
          npm ci
          npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.TEST_HOST }} >> ~/.ssh/known_hosts


      - name: Copy files to server
        run: |
          scp -r ./dist ${{ secrets.TEST_USER }}@${{ secrets.TEST_HOST }}:${{ secrets.TEST_REMOTE_PATH }}

      - name: Restart PM2
        run: |
          ssh ${{ secrets.TEST_USER }}@${{ secrets.TEST_HOST }} "cd ${{ secrets.TEST_REMOTE_PATH }} && pm2 restart mini_node_reports_server"
