name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.TEST_HOST }} >> ~/.ssh/known_hosts

      - name: Copy dist and package files to server
        run: |
          ssh ${{ secrets.TEST_USER }}@${{ secrets.TEST_HOST }} "mkdir -p ${{ secrets.TEST_REMOTE_PATH }}"
          scp -r ./dist ${{ secrets.TEST_USER }}@${{ secrets.TEST_HOST }}:${{ secrets.TEST_REMOTE_PATH }}
          scp ./package.json ./package-lock.json ${{ secrets.TEST_USER }}@${{ secrets.TEST_HOST }}:${{ secrets.TEST_REMOTE_PATH }}

      - name: Install production dependencies on server
        run: |
          ssh ${{ secrets.TEST_USER }}@${{ secrets.TEST_HOST }} "cd ${{ secrets.TEST_REMOTE_PATH }} && npm install --production"

      - name: Restart PM2
        run: |
          ssh ${{ secrets.TEST_USER }}@${{ secrets.TEST_HOST }} "cd ${{ secrets.TEST_REMOTE_PATH }} && pm2 restart mini_node_reports_server || pm2 start dist/server.js --name mini_node_reports_server"
